<?php

namespace App;

use App\Classes\ParseMarkdown;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\Tags\HasTags;

class Blog extends Model
{
    use HasTags;

    protected $guarded = [];

    protected $casts = [
        'is_published' => 'bool',
        'is_featured' => 'bool',
    ];

    protected $dates = ['published_at'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($blog) {
            $blog->slug = Str::slug($blog->title);
        });
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function scopePublished($query)
    {
        return $query->where([
            ['is_published','=',true],
            ['published_at','<=', now()]
        ]);
    }

    public function toHtml()
    {
        return (new ParseMarkdown())->text($this->body);
    }




}
